# Generated by Django 5.2 on 2025-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='piloto',
            name='steam_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
