# Generated by Django 5.2 on 2025-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_evento_download_url_piloto_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos/'),
        ),
    ]
