# Generated by Django 5.2 on 2025-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_event_formato_alter_community_logo_delete_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='patreon_url',
            field=models.URLField(blank=True),
        ),
    ]
