# Generated by Django 5.2 on 2025-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_community_patreon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='nombre',
            field=models.CharField(choices=[('AC', 'Assetto Corsa'), ('ACC', 'Assetto Corsa Competizione'), ('LMU', 'Le Mans Ultimate'), ('REN', 'Rennsport'), ('ACEVO', 'Assetto Corsa Evo')], max_length=50),
        ),
    ]
