# Generated by Django 5.2 on 2025-05-02 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_piloto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campeonato',
            new_name='Championship',
        ),
        migrations.RenameModel(
            old_name='Juego',
            new_name='Game',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='comunidad',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='driver/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('steam_id', models.CharField(blank=True, max_length=100)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='communities.community')),
            ],
        ),
        migrations.RenameModel(
            old_name='Evento',
            new_name='Event',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='communities.event')),
            ],
        ),
        migrations.DeleteModel(
            name='FechaEvento',
        ),
        migrations.DeleteModel(
            name='Piloto',
        ),
    ]
