# Generated by Django 5.2 on 2025-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_rename_campeonato_championship_rename_juego_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='formato',
            field=models.CharField(default='pactice: 20h qualy: 15m race: 40m', max_length=100),
        ),
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/community_logos/'),
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
